### ISSUE TITLE
path_not_found issue in generating response

### ISSUE THREAD

**Issue by Xiaoqianhou** [nyu-mll/nlu-test-sets#1]
When trying to repeat your experiment on mrqa_natural_questions dataset, I found that in the generating response step, in  'call_predict.py' we need to find some files in this path : _**output_path= cur_dir + '/scratch/pmh330/nyu-mll-jiant/experiments/'+'output_dir/taskmaster_'+model_name.strip()+'_bestconfig/'+task_name+'/*/*model*.p'**_.  But in the former steps this path is not create. And in the whole package of codes, the only place that is relevant to this path is in the 'save_test_examples.py' which is never ran before, and the path in 'save_test_examples.py' is : **_path=os.path.join('/scratch/pmh330/'+'nyu-mll-jiant/raw_examples',fname))_**    , still different from the path needed in 'call_predict.py'
Thanks a ton if you can help me explain this!

**Comment by claravania** [comment]
Hi @Xiaoqianhou,

That path refers to the path of your model checkpoint, so you'd need to change it so that it is pointing to your path. For training models and generating responses, you can follow the README provided [here](https://github.com/nyu-mll/nlu-test-sets/tree/main/jiant_scripts).
