### ISSUE TITLE
question about the training step in jiant

### ISSUE THREAD

**Issue by Xiaoqianhou** [nyu-mll/nlu-test-sets#2]
Hello~ We wanted to replicate what you have done in jiant (following this instruction https://github.com/nyu-mll/nlu-test-sets/tree/main/jiant_scripts)  but we found that the 'Training a model' step is too time-consuming for us. So we wanted to skip this step (we can do the tokenizing , we just want to skip training step) and use the pretrained models we download in the 'Downloading pretrained models' step to generate responses. But after trying for a few days we still don't get any success. So we want to ask that is it possible to do the things we want? If possible, could you please kindly give us some instructions? about where we have to change in your code?
We'd be really thankful if you can give us some advice!
Thank you in advance

**Comment by sleepinyourhat** [comment]
The ~18 pretrained models there are things like BERT encoders, which extract representations for text, but don't produce any output.

I'm sorry to say, I don't believe we don't have the full _task_-trained models from the paper available. They're huge, and the overhead of uploading/storing them is larger than just rerunning fine-tuning.

**Comment by Xiaoqianhou** [comment]
oh okay then~ Thank you for your answer!

在2021-07-23 22:36:14，Sam ***@***.***写道：

The ~18 pretrained models there are things like BERT encoders, which extract representations for text, but don't produce any output.

I'm sorry to say, I don't believe we don't have the full task-trained models from the paper available. They're huge, and the overhead of uploading/storing them is larger than just rerunning fine-tuning.
